---

- name: git clone rdma-bench and herd
  git:
    repo: 'https://github.com/efficient/rdma_bench.git'
    dest: "{{home_dir}}/"

- name: install related packages
  apt:
    name: "{{item}}"
  with_items:
    - 'cmake'
    - 'memcached'
    - 'libmemcached-dev'
    - 'libmemcached-tools'
    - 'libnuma-dev'
    - 'libpapi5.4.3'
    - 'libpapi-dev'
    - 'libgflags-dev'
    - 'numactl'

- name: make build dir
  file:
    path: "{{home_dir}}/rdma_bench/build"
    state:directory

- name: cmake rdma_bench
  shell: "{{item}}"
  args:
    chdir: "{{home_dir}}/rdma_bench/build"
  with_items:
    - "cmake .."
    - "make"





