---

- name: apt install packages
    apt:
      name: "{{packages}}"
    vars:
      packages:
        - libnuma-dev
        - libgflags-dev
        - libgtest-dev
        - libboost-dev
        - dpdk
        - libdpdk-dev
        - dpdk-igb-uio-dkms


- name: git clone efficient/eRPC
  git:
    repo: 'https://github.com/efficient/eRPC.git'
    dest: "{{home_dir}}/eRPC"


# pending dpdk setup scripts for cloudlab
