---

- name: untar crail incubator release
  when: inventory_hostname in groups['first_node']
  unarchive:
    src: "http://apache.claz.org/incubator/crail/1.0-incubating/apache-crail-1.0-incubating-src.tar.gz"
    dest: "{{home_dir}}"
    remote_src: yes

- name: install related packages
  apt:
    name: "{{item}}"
  with_items:
    - 'maven'
    - 'default-jdk'
  become: yes

- name: build crail with maven
  when: inventory_hostname in groups['first_node']
  shell: "mvn -DskipTests install"
  args:
    chdir: "{{home_dir}}/apache-crail-1.0-incubating-src"

- name: create crail bin folder
  file:
    path: "{{crail_bin_dir}}"
    state: directory

- name: copy crail tar to all servers
  unarchive:
    src: "{{home_dir}}/apache-crail-1.0-incubating-src/assembly/target/crail-1.0-bin.tar.gz"
    dest: "{{crail_bin_dir}}"

- name: set env CRAIL_HOME
  lineinfile:
    path: "{{home_dir}}/.bashrc"
    line: "{{item}}"
  with_items:
    - "export CRAIL_HOME={{crail_bin_dir}}"
    - "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"

# DiSNI 1.5 is required for apache-crail-1.0 release
- name: untar DiSNI 1.5
  unarchive:
    src: "https://github.com/zrlio/disni/archive/v1.5.tar.gz"
    dest: "{{home_dir}}"
    remote_src: yes

#- name: git clone DiSNI from ibm
#  git:
#    repo: 'https://github.com/zrlio/disni'
#    dest: "{{home_dir}}/disni"

- name: build DiSNI with maven
  shell: "mvn -DskipTests install"
  args:
    chdir: "{{home_dir}}/disni-1.5"

- name: make libdisni
  shell: "./autoprepare.sh && ./configure --with-jdk=/usr/lib/jvm/java-8-openjdk-amd64 && make && sudo make install"
  args:
    chdir: "{{home_dir}}/disni-1.5/libdisni/"

- name: copy libdisni.so to crail folder
  copy:
    src: "{{home_dir}}/disni-1.5/libdisni/src/.libs/libdisni.so"
    dest: "{{crail_bin_dir}}/lib/"

#- name: set hugetable and SHM limits
#  shell: "{{item}}"
#  with_items:
#    - 'echo 8192 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'
#    - 'bash -c "echo kernel.shmmax = 9223372036854775807 >> /etc/sysctl.conf"'
#    - 'bash -c "echo kernel.shmall = 1152921504606846720 >> /etc/sysctl.conf"'
#    - 'sysctl -p /etc/sysctl.conf'
#  become: yes


