- name: apt prepare software-properties-common
  apt:
    name: software-properties-common
  become: yes

- name: add g++7 repo
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test
    state: present
  become: yes

- name: install g++7
  apt:
    name: g++-7
    update_cache: yes
  become: yes
