- name: untar mellanox OFED
  unarchive:
    #src: "http://content.mellanox.com/ofed/MLNX_OFED-4.4-2.0.7.0/MLNX_OFED_LINUX-4.4-2.0.7.0-ubuntu16.04-x86_64.tgz"
    src: "http://content.mellanox.com/ofed/MLNX_OFED-4.5-1.0.1.0/MLNX_OFED_LINUX-4.5-1.0.1.0-ubuntu18.04-x86_64.tgz"
    dest: "{{tmp_dir}}"
    remote_src: yes

- name: install mellanox OFED
  shell: "./mlnxofedinstall --all --force"
  args:
    #chdir: "{{tmp_dir}}/MLNX_OFED_LINUX-4.4-2.0.7.0-ubuntu16.04-x86_64/"
    chdir: "{{tmp_dir}}/MLNX_OFED_LINUX-4.5-1.0.1.0-ubuntu18.04-x86_64/"
  become: yes

#- name: reload ofed driver
  #shell: "/etc/init.d/openibd restart"
  #become: yes

