---

- name: git clone octopus
  git:
    repo: 'https://github.com/lzhzero/octopus.git'
    dest: "{{home_dir}}/octopus"


- name: make build dir
  file:
    path: "{{home_dir}}/octopus/build"
    state: directory

- name: install related packages
  apt:
    name: "{{item}}"
  with_items:
    - 'cmake'
    - 'default-jdk'
    - 'mpich'
    - 'libcrypto++-dev'
    - 'libfuse2'
    - 'libfuse-dev'
  become: yes

- name: cmake octpus
  shell: "{{item}}"
  args:
    chdir: "{{home_dir}}/octopus/build"
  with_items:
    - "cmake .."
    - "make"

- name: copy conf.xml
  copy:
    src: "{{home_dir}}/octopus/conf.xml"
    dest: "{{home_dir}}/octopus/build/conf.xml"

#Hugetable may be optional for this
- name: set hugetable and SHM limits
  shell: "{{item}}"
  with_items:
    - 'echo 8192 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'
    - 'bash -c "echo kernel.shmmax = 9223372036854775807 >> /etc/sysctl.conf"'
    - 'bash -c "echo kernel.shmall = 1152921504606846720 >> /etc/sysctl.conf"'
    - 'sysctl -p /etc/sysctl.conf'
  become: yes




